/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SocialPost = IDL.Record({
  'hashtags' : IDL.Vec(IDL.Text),
  'platform' : IDL.Text,
  'caption' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'product' : Product,
});
export const BrandProfile = IDL.Record({
  'categories' : IDL.Vec(IDL.Text),
  'logo' : ExternalBlob,
  'name' : IDL.Text,
  'tone' : IDL.Text,
  'audience' : IDL.Text,
  'catalog' : IDL.Vec(Product),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PostStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const Time = IDL.Int;
export const ScheduledPost = IDL.Record({
  'status' : PostStatus,
  'scheduledTime' : Time,
  'post' : SocialPost,
  'brandId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([IDL.Text, Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBrandProfile' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'deleteScheduledPost' : IDL.Func([IDL.Text], [], []),
  'generatePost' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [SocialPost], []),
  'getBrandProfile' : IDL.Func([IDL.Text], [IDL.Opt(BrandProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getScheduledPosts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ScheduledPost)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'schedulePost' : IDL.Func([IDL.Text, SocialPost, Time], [IDL.Text], []),
  'updatePostStatus' : IDL.Func([IDL.Text, PostStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SocialPost = IDL.Record({
    'hashtags' : IDL.Vec(IDL.Text),
    'platform' : IDL.Text,
    'caption' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'product' : Product,
  });
  const BrandProfile = IDL.Record({
    'categories' : IDL.Vec(IDL.Text),
    'logo' : ExternalBlob,
    'name' : IDL.Text,
    'tone' : IDL.Text,
    'audience' : IDL.Text,
    'catalog' : IDL.Vec(Product),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PostStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Time = IDL.Int;
  const ScheduledPost = IDL.Record({
    'status' : PostStatus,
    'scheduledTime' : Time,
    'post' : SocialPost,
    'brandId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([IDL.Text, Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBrandProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'deleteScheduledPost' : IDL.Func([IDL.Text], [], []),
    'generatePost' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [SocialPost], []),
    'getBrandProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BrandProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getScheduledPosts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ScheduledPost)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'schedulePost' : IDL.Func([IDL.Text, SocialPost, Time], [IDL.Text], []),
    'updatePostStatus' : IDL.Func([IDL.Text, PostStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };